edition = "2021"
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
combine_control_expr = false
condense_wildcard_suffixes = false
empty_item_single_line = false
fn_params_layout = "Vertical"
fn_single_line = true
format_code_in_doc_comments = true
max_width = 80
merge_derives = true
reorder_imports = false
reorder_modules = false
struct_lit_single_line = true
where_single_line = false
